const universitiesFrance = [
    "Université d'Aix-Marseille (AMU)",
    "Université Paris 1 Panthéon-Sorbonne",
    "Université Paris-Saclay",
    "Université Paris Diderot (Paris 7)",
    "Université de Lyon",
    "Université de Strasbourg",
    "Université de Toulouse",
    "Université de Bordeaux",
    "Université de Lille",
    "Université Grenoble Alpes",
    "Université de Montpellier",
    "Université de Nantes",
    "Université de Rennes 1",
    "Université de Rouen Normandie",
    "Université de Clermont Auvergne",
    "Université de Bretagne Occidentale",
    "Université de Franche-Comté",
    "Université de Caen Normandie",
    "Université de Poitiers",
    "Université d'Orléans",
    "Université de Tours",
    "Université de la Réunion",
    "Université de La Rochelle",
    "Université de Chambéry",
    "Université de Lorraine",
    "Université de Picardie Jules Verne",
    "Université de Valenciennes et du Hainaut-Cambrésis",
    "Université de Dijon",
    "Université de Limoges",
    "Université de Nîmes",
    "Université de Perpignan Via Domitia",
    "Université d'Angers",
    "Université de Grenoble Alpes",
    "Université de Metz",
    "Université de Mayotte",
    "Université de Saint-Étienne",
    "Université de Corse Pasquale Paoli",
    "Université de Paris (ex-Paris 5, Paris 6, Paris 7)",
    "Université de Lille 3 (Sciences humaines et sociales)",
    "Université de Poitiers",
    "Université de La Réunion",
    "Université de Picardie Jules Verne",
    "Université de Rouen",
    "Université de Savoie Mont-Blanc",
    "Université de Nice Sophia Antipolis",
    "Université de l'Académie de Corse",
    "Université de Tours",
    "Université Jean Moulin Lyon 3",
    "Université Paris-Est Marne-la-Vallée",
    "Université de Bordeaux Montaigne",
    "Université de Bretagne-Sud",
    "Université de Toulouse-Jean-Jaurès",
    "Université de Paris-Nanterre",
    "Université Paul Sabatier Toulouse 3",
    "Université de Sciences et Technologies de Lille",
    "Université de Cergy-Pontoise",
    "Université de Versailles Saint-Quentin-en-Yvelines",
    "Université du Maine"
];

console.log("Liste des universités de France :");
universitiesFrance.forEach((university, index) => {
    console.log(`${index + 1}. ${university}`);
});